## Building predictive models

In [7]:
import numpy as np
import os
import pandas as pd

### Import Data 

In [8]:
#set the path of processed data
processed_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(processed_data_path,'train.csv')
test_file_path = os.path.join(processed_data_path,'test.csv')

In [9]:
train_df = pd.read_csv(train_file_path,index_col='PassengerId')
test_df = pd.read_csv(test_file_path,index_col='PassengerId')

In [10]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [11]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

### Data Preparation 

In [12]:
X = train_df.loc[:,'Age':].as_matrix().astype('float')
Y = train_df['Survived'].ravel()

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [13]:
print X.shape, Y.shape

(891, 32) (891,)


In [14]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print X_train.shape, Y_train.shape
print X_test.shape, Y_test.shape

(712, 32) (712,)
(179, 32) (179,)


In [15]:
#average survival in train and test
print 'mean survival in train : {0:.3f}'.format(np.mean(Y_train))
print 'mean survival in test : {0:.3f}'.format(np.mean(Y_test))

mean survival in train : 0.383
mean survival in test : 0.385


#### Check SciKit Learn version

In [16]:
import sklearn
sklearn.__version__

'0.20.1'

In [17]:
#!conda update -y scikit-learn

###  Baseline model

In [18]:
#import function
from sklearn.dummy import DummyClassifier

In [19]:
#create model
model_dummy = DummyClassifier(strategy='most_frequent',random_state=0)

In [20]:
#train model
model_dummy.fit(X_train,Y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [21]:
print 'score for baseline model : {0:.2f}'.format(model_dummy.score(X_test,Y_test))

score for baseline model : 0.61


In [22]:
#performance metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [23]:
#accuracy score
print 'accuracy for the baseline model : {0:.2f}'.format(accuracy_score(Y_test,model_dummy.predict(X_test)))

accuracy for the baseline model : 0.61


In [24]:
#confusion matrix
print 'confusion matrix for the baseline model : \n {0}'.format(confusion_matrix(Y_test,model_dummy.predict(X_test)))

confusion matrix for the baseline model : 
 [[110   0]
 [ 69   0]]


In [25]:
#precision and recall scores
print 'precision for the baseline model : {0:.2f}'.format(precision_score(Y_test,model_dummy.predict(X_test)))
print 'recall for the baseline model : {0:.2f}'.format(recall_score(Y_test,model_dummy.predict(X_test)))

precision for the baseline model : 0.00
recall for the baseline model : 0.00


/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### First Kaggle submission 

In [26]:
#covert to matrix
test_X = test_df.as_matrix().astype('float')

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [27]:
#get predictions
predictions = model_dummy.predict(test_X)

In [28]:
df_submission=pd.DataFrame({'PassengerId':test_df.index, 'Survived':predictions})

In [29]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [ ]:
submission_data_path = os.path.join(os.path.pardir,'data','external')
submission_file_path = os.path.join(submission_data_path,'01_dummy.csv')

In [ ]:
df_submission.to_csv(submission_file_path,index=False)

In [40]:
def get_submission_file(model,filename):
    #covert to matrix
    test_X = test_df.as_matrix().astype('float')
    #get predictions
    predictions = model.predict(test_X)
    df_submission=pd.DataFrame({'PassengerId':test_df.index, 'Survived':predictions})
    submission_data_path = os.path.join(os.path.pardir,'data','external')
    submission_file_path = os.path.join(submission_data_path,filename)
    df_submission.to_csv(submission_file_path,index=False)

In [ ]:
get_submission_file(model_dummy,'01_dummy.csv')

### Logistic Regression Model

In [2]:
#import function
from sklearn.linear_model import LogisticRegression

In [26]:
#create model
model_lr_1 = LogisticRegression(random_state=0)

In [27]:
# train model
model_lr_1.fit(X_train,Y_train)

/anaconda2/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [28]:
#valuate model
print 'Score of Logistic Regression - version 1 : {0:.2f}'.format(model_lr_1.score(X_train,Y_train))

Score of Logistic Regression - version 1 : 0.84


In [29]:
#accuracy score
print 'accuracy for the Logistic Regression model  : {0:.2f}'.format(accuracy_score(Y_test,model_lr_1.predict(X_test)))
#confusion matrix
print 'confusion matrix for the Logistic Regression model : \n {0}'.format(confusion_matrix(Y_test,model_lr_1.predict(X_test)))
#precision and recall scores
print 'precision for the Logistic Regression model : {0:.2f}'.format(precision_score(Y_test,model_lr_1.predict(X_test)))
print 'recall for the Logistic Regression model : {0:.2f}'.format(recall_score(Y_test,model_lr_1.predict(X_test)))

accuracy for the Logistic Regression model  : 0.83
confusion matrix for the Logistic Regression model : 
 [[95 15]
 [16 53]]
precision for the Logistic Regression model : 0.78
recall for the Logistic Regression model : 0.77


In [30]:
#model coefficient
model_lr_1.coef_

array([[-0.02923553,  0.00451899, -0.50687734,  0.66961288,  0.        ,
         0.10012052, -0.18832707, -0.41398124,  0.51092837,  1.08121044,
         0.38318919, -0.19260299, -0.33615771,  0.89986506,  0.43281204,
        -0.38829759,  0.37731842,  0.91161511,  0.98600282, -1.81358953,
         1.46349644, -0.3356932 , -0.64477056,  0.1166403 ,  0.19947119,
         0.24640572,  0.3818623 ,  0.44346438,  0.40641003,  0.0945051 ,
         0.30654211,  0.63783741]])

### Second Kaggle Submission 

In [ ]:
get_submission_file( model_lr_1,'02_lr.csv')

### HyperParameter Optimisation

In [30]:
# base model
model_lr = LogisticRegression(random_state=0)

In [31]:
from sklearn.model_selection import GridSearchCV

In [32]:
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' : ['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)

In [33]:
clf.fit(X_train, Y_train)

/anaconda2/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [34]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [36]:
print 'best score : {0:.2f}'.format(clf.best_score_)

best score : 0.83


In [38]:
#evaluate model
print 'score for logistic regression - version 2 : {0:.2f}'.format(clf.score(X_test,Y_test))

score for logistic regression - version 2 : 0.83


### Making 3rd submission 

In [41]:
#get submission file
get_submission_file(clf,'03_lr.csv')

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


### Feature Normalization and Standardization 

In [42]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

#### Feature Normalization

In [43]:
# feature normalization
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [44]:
X_train_scaled[:,0].min(),X_train_scaled[:,0].max()

(0.0, 1.0)

In [45]:
# normalize test data
X_test_scaled = scaler.transform(X_test)

#### Feature Standardization

In [46]:
# feature standardization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#### Create model after standardiation

In [48]:
# base model 
model_lr = LogisticRegression(random_state=0)
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' : ['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)
clf.fit(X_train_scaled, Y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [49]:
clf.best_score_

0.8146067415730337

In [51]:
# evaluate model
print 'score for logistic regression - version 2 : {0:.2f}'.format(clf.score(X_test_scaled, Y_test))

score for logistic regression - version 2 : 0.84


### Model Peristence 

In [52]:
# import pickle library
import pickle

In [53]:
# create the file paths
model_file_path = os.path.join(os.path.pardir,'models','lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir,'models','lr_scaler.pkl')

In [54]:
# open the files to write 
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [55]:
# persist the model and scaler
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler, scaler_file_pickle)

In [56]:
# close the file
model_file_pickle.close()
scaler_file_pickle.close()

#### load the persisted file

In [57]:
# open files in read mode
model_file_pickle = open(model_file_path, 'r')
scaler_file_pickle = open(scaler_file_path, 'r')
# load files
clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)
# close files
model_file_pickle.close()
scaler_file_pickle.close()

In [58]:
clf_loaded

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [59]:
scaler_loaded

StandardScaler(copy=True, with_mean=True, with_std=True)

In [77]:
# transform the test data using loaded scaler object
X_test_scaled = scaler_loaded.transform(X_test)
# calculate the score using loaded model object 
print 'score for persisted logistic regression : {0:.2f}'.format(clf_loaded.score(X_test_scaled, Y_test))

score for persisted logistic regression : 0.84
